collection = "App"

### private repositories:
# filter = ["SshKey=/full/path/to/ssh/keys.toml"]

[[package]]
name = "firewalld"
repository = "https://github.com/pintoflager/carburator-app-firewalld.git"
platforms = ["Client", "Server"]
filter = ["Provides=firewall"]

[[package]]
name = "haproxy"
repository = "https://github.com/pintoflager/carburator-app-haproxy.git"
platforms = ["Server"]
filter = ["Provides=proxy"]

[[package]]
name = "nginx"
repository = "https://github.com/pintoflager/carburator-app-nginx.git"
platforms = ["Server"]
filter = ["Provides=proxy"]
