collection = "App"

[[package]]
name = "haproxy"
version = "0.1.0"
repository = "https://github.com/pintoflager/carburator-app-haproxy.git"
targets = ["Worker"]
priority = 10
dependencies = []
provides = ["loadbalancer"]
