collection = "App"

# TODO: keys.toml not present anymore. This could just try all keys of user instead?
### private repositories:
# filter = ["SshKey=/full/path/to/ssh/keys.toml"]

[[package]]
name = "git"
repository = "https://github.com/pintoflager/carburator-app-git/archive/refs/tags/0.1.5.tar.gz"
platforms = ["Client"]
filter = ["Provides=git"]

[[package]]
name = "firewalld"
repository = "https://github.com/pintoflager/carburator-app-firewalld.git"
platforms = ["Client", "Server"]
filter = ["Provides=firewall"]

[[package]]
name = "tester"
repository = "https://github.com/pintoflager/carburator-app-tester.git"
platforms = ["Client", "Server"]
filter = ["Provides=tester"]
