collection = "app"

[[package]]
name = "haproxy"
version = "0.1.0"
repository = "https://github.com/pintoflager/carburator-app-haproxy.git"
targets = ["production", "staging"]
priority = 10
install_on = "remote"
peer_dependencies = []
provides = ["loadbalancer"]
