collection = "App"

### private repositories:
# filter = ["SshKey=/full/path/to/ssh/keys.toml"]

[[package]]
name = "firewalld"
repository = "https://github.com/pintoflager/carburator-app-firewalld.git"
platforms = ["Client", "Server"]
filter = ["Provides=firewall"]

[[package]]
name = "tester"
repository = "https://github.com/pintoflager/carburator-app-tester.git"
platforms = ["Client", "Server"]
filter = ["Provides=tester"]
