collection = "App"

[[package]]
name = "haproxy"
repository = "https://github.com/pintoflager/carburator-app-haproxy.git"
platforms = ["Worker"]
priority = 10
dependencies = []
provides = ["loadbalancer"]
