collection = "App"

[[package]]
name = "haproxy"
repository = "https://github.com/pintoflager/carburator-app-haproxy.git"
platforms = ["Worker"]
filter = ["Provides=proxy"]

[[package]]
name = "nginx"
repository = "https://github.com/pintoflager/carburator-app-nginx.git"
platforms = ["Worker"]
filter = ["Provides=proxy"]
