collection = "apps"

[[package]]
name = "haproxy"
version = "0.1.0"
repository = "https://github.com/pintoflager/carburator-app-haproxy.git"
targets = ["production", "staging"]

[[package.requirements]]
local = []
remote = []

[[package.secret]]
key = "haproxy_user"
generate = "user" # TODO: not making any sense. username is not secret.

[[package.secret]]
key = "haproxy_pass"
generate = "password"
