ssh_port = 22
# Disables SSH login with username + password (only private/public key logins).
ssh_password_auth = false

[scripts]
register = "register"
install = "install"
update = "update"
destroy = "destroy"
exitcode_not_found = 100
exitcode_can_retry = 110
exitcode_unrecoverable = 120

[node]
# Number of nodes to tag as 'proxies'. Only server nodes with public IP addresses
# will be selected.
proxies = 2
# Disables remote node system crons and only systemd based carburator crons
# can be used.
syscron = false

[node.server]
hostname_set = false
ipv4 = true
ipv6 = true
# Max number of database nodes for the project
databases = 3
cluster_names = ["apricot", "avocado", "banana", "blackberry",
	"blueberry", "carambola", "cherry", "cloudberry", "coconut", "cranberry", "damson",
	"dragonfruit", "elderberry", "feijoa", "fig", "grape", "grapefruit", "grapes", "grewia",
	"guava", "hanepoot", "huckleberry", "jackfruit", "jamun", "jicama", "jujube", "kiwano", "kiwi",
	"lemon", "lime", "longan", "loquat", "lychee", "mandarin", "mango", "melon", "mulberry",
	"muskmelon", "nance", "nectarine", "olive", "orange", "papaya", "peach", "pear", "persimmon",
	"pineapple", "plum", "pomegranate", "pumpkin", "quince", "sapodilla", "satsuma",
	"shaddock", "soursop", "strawberry", "sugarcane", "tamarillo", "tamarind", "tangerine",
	"watermelon"]

[node.client]
ipv4 = true
ipv6 = true
cluster_names = ["clients"]

[providers]
