ssh_port = 22
ssh_password_auth = false

[scripts]
package_install = "install"
package_update = "update"
package_destroy = "destroy"
exitcode_not_found = 100
exitcode_can_retry = 110
exitcode_unrecoverable = 120

[node]
proxies = 2

[node.server]
ipv4 = true
ipv6 = true
cluster_names = ["apricot", "avocado", "banana", "blackberry",
	"blueberry", "carambola", "cherry", "cloudberry", "coconut", "cranberry", "damson", "dates",
	"dragonfruit", "elderberry", "feijoa", "fig", "grape", "grapefruit", "grapes", "grewia",
	"guava", "hanepoot", "huckleberry", "jackfruit", "jamun", "jicama", "jujube", "kiwano", "kiwi",
	"lemon", "lime", "longan", "loquat", "lychee", "mandarin", "mango", "melon", "mulberry",
	"muskmelon", "nance", "nectarine", "olive", "orange", "papaya", "peach", "pear", "persimmon",
	"pineapple", "plum", "pomegranate", "pumpkin", "quince", "sapodilla", "satsuma",
	"shaddock", "soursop", "strawberry", "sugarcane", "tamarillo", "tamarind", "tangerine",
	"watermelon"]

[node.client]
ipv4 = true
ipv6 = true
cluster_names = ["clients", "watchdogs"]

[providers]
