ssh_port = 22

[scripts]
executor = "python"
package_init = "install"
exitcode_not_found = 100
exitcode_can_retry = 110
exitcode_unrecoverable = 120

[node.worker]
ipv4 = true
ipv6 = true
private_net = true
group_names = ["apple", "apricot", "avocado", "banana", "blackberry",
	"blueberry", "carambola", "cherry", "cloudberry", "coconut", "cranberry", "damson", "dates",
	"dragonfruit", "elderberry", "feijoa", "fig", "grape", "grapefruit", "grapes", "grewia",
	"guava", "hanepoot", "huckleberry", "jackfruit", "jamun", "jicama", "jujube", "kiwano", "kiwi",
	"lemon", "lime", "longan", "loquat", "lychee", "mandarin", "mango", "melon", "mulberry",
	"muskmelon", "nance", "nectarine", "olive", "orange", "papaya", "peach", "pear", "persimmon",
	"pineapple", "plum", "pomegranate", "pumpkin", "quince", "raspberry", "sapodilla", "satsuma",
	"shaddock", "soursop", "strawberry", "sugarcane", "tamarillo", "tamarind", "tangerine",
	"watermelon"]

[node.commander]
ipv4 = true
ipv6 = true
private_net = true
group_names = ["devs", "watchdogs"]

[providers]