collection = "Executor"
path = "executors"

[[package]]
name = "ansible"
version = "0.1.0"
repository = "https://github.com/pintoflager/carburator-executor-ansible.git"
project_roles = ["Commander"]

[[package]]
name = "bash"
version = "0.1.0"
repository = "https://github.com/pintoflager/carburator-executor-bash.git"
project_roles = ["Worker"]

[[package]]
name = "python"
version = "0.1.0"
repository = "https://github.com/pintoflager/carburator-executor-python.git"
project_roles = ["Worker"]
