collection = "Executor"
path = "executors"

[[package]]
name = "ansible"
repository = "https://github.com/pintoflager/carburator-executor-ansible.git"
platforms = ["Commander"]

[[package]]
name = "bash"
repository = "https://github.com/pintoflager/carburator-executor-bash.git"
platforms = ["Commander", "Worker"]

[[package]]
name = "python"
repository = "https://github.com/pintoflager/carburator-executor-python.git"
platforms = ["Commander", "Worker"]
