collection = "Executor"
path = "executors"

[[package]]
name = "sh"
repository = "https://github.com/pintoflager/carburator-executor-sh/archive/refs/tags/0.1.2.tar.gz"
platforms = ["Client", "Server"]

[[package]]
name = "bash"
repository = "https://github.com/pintoflager/carburator-executor-bash.git"
# repository = "https://github.com/pintoflager/carburator-executor-bash/archive/refs/tags/0.1.2.tar.gz"
platforms = ["Client", "Server"]

[[package]]
name = "python"
repository = "https://github.com/pintoflager/carburator-executor-python.git"
# repository = "https://github.com/pintoflager/carburator-executor-python/archive/refs/tags/0.1.2.tar.gz"
platforms = ["Client", "Server"]

[[package]]
name = "ansible"
repository = "https://github.com/pintoflager/carburator-executor-ansible.git"
# repository = "https://github.com/pintoflager/carburator-executor-ansible/archive/refs/tags/0.1.2.tar.gz"
platforms = ["Client"]

[[package]]
name = "perl"
repository = "https://github.com/pintoflager/carburator-executor-perl.git"
# repository = "https://github.com/pintoflager/carburator-executor-perl/archive/refs/tags/0.1.0.tar.gz"
platforms = ["Client", "Server"]

[[package]]
name = "lua"
repository = "https://github.com/pintoflager/carburator-executor-lua.git"
# repository = "https://github.com/pintoflager/carburator-executor-lua/archive/refs/tags/0.1.0.tar.gz"
platforms = ["Client", "Server"]
