collection = "Executor"
path = "executors"

[[package]]
name = "sh"
repository = "https://github.com/pintoflager/carburator-executor-sh.git"
platforms = ["Client", "Commander", "Worker"]

[[package]]
name = "ansible"
repository = "https://github.com/pintoflager/carburator-executor-ansible.git"
platforms = ["Client", "Commander"]

[[package]]
name = "bash"
repository = "https://github.com/pintoflager/carburator-executor-bash.git"
platforms = ["Client", "Commander", "Worker"]

[[package]]
name = "python"
repository = "https://github.com/pintoflager/carburator-executor-python.git"
platforms = ["Client", "Commander", "Worker"]
