collection = "provisioners"

[[items]]
name = "api"
version = "0.1.0"
repository = "https://github.com/pintoflager/carburator-provisioner-api.git"
targets = ["production", "staging"]
requirements = []

[[items]]
name = "terraform"
version = "0.1.0"
repository = "https://github.com/pintoflager/carburator-provisioner-terraform.git"
targets = ["production", "staging"]
requirements = ["terraform"]

