collection = "Provisioner"
path = "provisioners"

[[package]]
name = "terraform"
version = "0.1.0"
repository = "https://github.com/pintoflager/carburator-provisioner-terraform.git"
project_roles = ["Commander"]
filter = ["ProviderType=ServiceProvider"]

[[package]]
name = "api"
version = "0.1.0"
repository = "https://github.com/pintoflager/carburator-provisioner-api.git"
project_roles = ["Commander"]
filter = ["ProviderType=DnsProvider"]
