collection = "provisioner"
path = "provisioners"

[[package]]
name = "terraform"
version = "0.1.0"
repository = "https://github.com/pintoflager/carburator-provisioner-terraform.git"
targets = ["commander"]

[[package]]
name = "api"
version = "0.1.0"
repository = "https://github.com/pintoflager/carburator-provisioner-api.git"
targets = ["commander"]
