collection = "Provisioner"
path = "provisioners"

[[package]]
name = "terraform"
repository = "https://github.com/pintoflager/carburator-provisioner-terraform.git"
platforms = ["Client"]
filter = ["ProviderType=ServiceProvider"]

[[package]]
name = "qemu"
repository = "https://github.com/pintoflager/carburator-provisioner-qemu.git"
platforms = ["Client"]
filter = ["ProviderType=ServiceProvider"]

[[package]]
name = "template"
repository = "https://github.com/pintoflager/carburator-provisioner-template/archive/refs/tags/0.1.0.tar.gz"
platforms = ["Client"]
filter = ["Select=false"]
