collection = "provisioner"
path = "provisioners"

[[package]]
name = "terraform"
version = "0.1.0"
repository = "https://github.com/pintoflager/carburator-provisioner-terraform.git"
targets = ["production", "staging"]
