collection = "dns"
path = "/providers/dns"

[[package]]
name = "localhost"
version = "0.1.0"
repository = "https://github.com/pintoflager/carburator-provider-dns-localhost.git"
targets = ["development"]
requirements = []

# Example:
# [[package.secret]]
# key = "localhost_dns_user"
# prompt = "DNS username managing localhost private hostnames."

# [[package.secret]]
# key = "localhost_dns_pass"
# prompt = "Password for DNS manager user"

[[package]]
name = "hetzner"
version = "0.1.0"
repository = "https://github.com/pintoflager/carburator-provider-dns-hezner.git"
targets = ["production", "staging"]
requirements = []

[[package.secret]]
name = "hetzner_dns_apikey"

[[package.secret.line]]
key = "apikey"
value = "prompt!(Hetzner DNS API key for managing domain names.)"