collection = "providers_dns"

[[items]]
name = "localhost"
version = "0.1.0"
repository = "https://github.com/pintoflager/carburator-provider-dns-localhost.git"
targets = ["development"]
requirements = []

# Example:
# [[items.secret]]
# key = "localhost_dns_user"
# prompt = "DNS username managing localhost private hostnames."

# [[items.secret]]
# key = "localhost_dns_pass"
# prompt = "Password for DNS manager user"

[[items]]
name = "hetzner"
version = "0.1.0"
repository = "https://github.com/pintoflager/carburator-provider-dns-hezner.git"
targets = ["production", "staging"]
requirements = []

[[items.secret]]
key = "hetzner_dns_apikey"
prompt = "Hetzner DNS API key for managing domain names."
