collection = "DnsProvider"
path = "providers/dns"

[[package]]
name = "mkcert"
version = "0.1.0"
repository = "https://github.com/pintoflager/carburator-provider-dns-mkcert.git"
project_roles = ["Playground"]

[[package]]
name = "hetzner"
version = "0.1.0"
repository = "https://github.com/pintoflager/carburator-provider-dns-hetzner.git"
project_roles = ["Commander", "Worker"]
