collection = "dns"
path = "providers/dns"

[[package]]
name = "localhost"
version = "0.1.0"
repository = "https://github.com/pintoflager/carburator-provider-dns-localhost.git"
targets = ["development"]

[[package]]
name = "hetzner"
version = "0.1.0"
repository = "https://github.com/pintoflager/carburator-provider-dns-hetzner.git"
targets = ["production", "staging"]
