collection = "DnsProvider"
path = "providers/dns"

[[package]]
name = "hetzner"
version = "0.1.0"
repository = "https://github.com/pintoflager/carburator-provider-dns-hetzner.git"
platforms = ["Commander", "Worker"]
