collection = "dns"
path = "providers/dns"

[[package]]
name = "mkcert"
version = "0.1.0"
repository = "https://github.com/pintoflager/carburator-provider-dns-mkcert.git"
targets = ["playground"]

[[package]]
name = "hetzner"
version = "0.1.0"
repository = "https://github.com/pintoflager/carburator-provider-dns-hetzner.git"
targets = ["commander", "worker"]
