collection = "GitProvider"
path = "providers/git"

[[package]]
name = "github"
repository = "https://github.com/pintoflager/carburator-provider-github.git"
platforms = ["Client"]

# [[package]]
# name = "template"
# repository = "https://github.com/pintoflager/carburator-provider-git-template/archive/refs/tags/0.1.0.tar.gz"
# platforms = ["Client"]
# filter = ["Select=false"]