collection = "ServiceProvider"
path = "providers/service"

[[package]]
name = "hetzner"
version = "0.1.0"
repository = "https://github.com/pintoflager/carburator-provider-service-hetzner.git"
platforms = ["Commander"]
