collection = "service"
path = "providers/service"

[[package]]
name = "localhost"
version = "0.1.0"
repository = "https://github.com/pintoflager/carburator-provider-service-localhost.git"
targets = ["development"]

[[package]]
name = "hetzner"
version = "0.1.0"
repository = "https://github.com/pintoflager/carburator-provider-service-hetzner.git"
targets = ["production", "staging"]
