collection = "ServiceProvider"
path = "providers/service"

[[package]]
name = "localhost"
version = "0.1.0"
repository = "https://github.com/pintoflager/carburator-provider-service-localhost.git"
project_roles = ["Playground"]

[[package]]
name = "hetzner"
version = "0.1.0"
repository = "https://github.com/pintoflager/carburator-provider-service-hetzner.git"
project_roles = ["Commander"]
